#!/usr/bin/env node
/*jslint node: true */

// All global variables here. {{{
// No further clobbering of the global object.
var optimist, argv,
    http, server;
// }}}

// Requires {{{
optimist = require('optimist');
http     = require('http');
// }}}

// Argument handling {{{
argv = optimist
    .usage('LUnix web server.\nUsage: $0')
    .options({
        'u': {
            alias:   'user',
            default: 'node'
        },
        'g': {
            alias:   'group',
            default: 'nogroup'
        },
        'l': {
            alias:   'listen',
            default: 'localhost'
        },
        'p': {
            alias:   'port',
            default: 8080
        },
        'h': {
            alias:   'help'
        },
        'v': {
            alias:   'verbose'
        }
    })
    .argv;

if (argv.help) {
    optimist.showHelp();
    process.exit(0);
}

// }}}

// Drop privileges {{{
if (argv.user) {
    console.log(argv.user);
    if (argv.verbose) {
        console.log('Dropping privileges to '
                    + argv.user
                    + ':'
                    + argv.group
                    + '...');
    }

    try {
        process.setgid(argv.group);
        process.setuid(argv.user);
    } catch (e) {
        console.log('Failed: ' + e.message);
        process.exit(1);
    }

    if (argv.verbose) {
        console.log('ok.');
    }
}
// }}}

// create server {{{
server = {};
server.server = new http.Server();
server.dispatch = require('./dispatcher.js');

if (argv.verbose) {
    console.log('Listening on host '
                + argv.listen
                + ', port '
                + argv.port
                + '.\n');
}


// Request handler {{{
server.server.on('request', function (request, response) {
    'use strict';
    server.dispatch(request.url)(request, response);
});
// }}}

server.server.listen(argv.port, argv.host);

if (argv.verbose) {
    console.log('ok.');
}
// }}}

// vim: filetype=javascript
